[package]
name = "qlip"
version = "0.1.0"
authors = ["toast"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
qr2term = "0.2.2"
